language: php
php: 7.4
branches:
  - only:
      - master

before_script:
  - composer install

script:
  - echo "START of Travis CI testing custom modules"
  - cp web/phpunit.xml web/core/phpunit.xml
  - cd web/core
  - ../../vendor/bin/phpunit --group=example_module_unit ../modules/custom
  - echo "END of Travis CI testing custom modules"
