language: php
php: 7.4
branches:
  - only:
      - master
addons:
  hosts:
    - drupal.localhost

before_install:
#  - mysql --version
#  - mysql -e 'CREATE DATABASE IF NOT EXISTS drupal_unit_tests;'
  - sudo apt-get autoremove sqlite3
  - sudo apt-get install python-software-properties
  - sudo apt-add-repository -y ppa:travis-ci/sqlite3
  - sudo apt-get -y update
  - sudo apt-cache show sqlite3
  - sudo apt-get install sqlite3=3.7.15.1-1~travis1
  - sudo sqlite3 -version
  - sudo psql --version
  - sudo mysql --version

before_script:
  - composer install
#  - cp web/sites/travis.settings.php web/sites/default/settings.php
#  - php web/core/scripts/drupal quick-start standard --site-name Drupal9PHPUnitTests --host drupal.localhost --port 80
  - vendor/bin/drush qd -y
  - cd web
  - php -S drupal.localhost:80

script:
  - echo "START of Travis CI testing custom modules"
  - curl http://drupal.localhost
  - cp web/phpunit.xml web/core/phpunit.xml
  - cd web/core
  - ../../vendor/bin/phpunit ../modules/custom
  - echo "END of Travis CI testing custom modules"
