language: php
php: 7.4
branches:
  - only:
      - master

before_script:
  - composer install

script:
  - echo "START of Travis CI testing custom modules"
  - cd web/core
  - ../../vendor/bin/phpunit -c ../phpunit.xml ../modules/custom
  - echo "END of Travis CI testing custom modules"
