language: php
php: 7.3
branches:
  - only:
      - master
addons:
  hosts:
    - drupal.localhost

before_install:
#  - mysql --version
#  - mysql -e 'CREATE DATABASE IF NOT EXISTS drupal_unit_tests;'

before_script:
  - composer install
#  - cp web/sites/travis.settings.php web/sites/default/settings.php
#  - php web/core/scripts/drupal quick-start standard --site-name Drupal9PHPUnitTests --host drupal.localhost --port 80
  - vendor/bin/drush qd --server=drupal.localhost:80 -y &
  - sleep 7
#  - cd web
#  - php -S drupal.localhost:80

script:
  - echo "START of Travis CI testing custom modules"
  - curl http://drupal.localhost
  - cp web/phpunit.xml web/core/phpunit.xml
  - cd web/core
  - ../../vendor/bin/phpunit ../modules/custom
  - echo "END of Travis CI testing custom modules"
